import CoreGraphics
import Foundation

/// A script's transactional view of the open documents (§6 for what that
/// buys). Each document is copied in as a `Document` value; every operation
/// the script performs mutates the copy through the pure ops in `Model/`;
/// nothing reaches a `DocumentStore` until `ScriptRunner` commits the touched
/// copies — one history entry per document, or nothing at all if the script
/// threw. The session is also what a CLI or MCP front end would drive: it is
/// plain Swift over plain values, with JSON in and JSON out.
///
/// Thread-agnostic and main-thread-free: the runner constructs it on main,
/// hands it to the script thread, and reads it back on main afterwards.
final class ScriptSession {
    struct WorkingDocument {
        let id: String
        var title: String
        /// The value the copy started from; the runner refuses to commit over
        /// a store whose document has since moved (§6 — no silent clobbers).
        let base: Document
        var document: Document
        let baseSelection: SelectionState
        var selection: SelectionState
        let baseSelectedLayerIDs: [UUID]
        var selectedLayerIDs: [UUID]
        /// Created by the script (`dezzy.newDocument`); the runner opens a
        /// real window for it on commit.
        let isNew: Bool

        var ids: ScriptState.IDMap { ScriptState.IDMap(document) }

        var isTouched: Bool {
            isNew || document != base || selection != baseSelection
                || selectedLayerIDs != baseSelectedLayerIDs
        }
    }

    private(set) var documents: [WorkingDocument] = []
    private(set) var activeID: String?
    /// Images a script can place: generated by a tool, loaded from disk, or
    /// rendered from a layer. Keyed by the id the script holds.
    private(set) var images: [String: CGImage] = [:]
    private var nextImageNumber = 1
    /// Hands out the id a new document will have in the registry, so the
    /// script can refer to it before it exists.
    private let reserveDocumentID: () -> String

    init(documents: [WorkingDocument], activeID: String?, reserveDocumentID: @escaping () -> String) {
        self.documents = documents
        self.activeID = activeID ?? documents.first?.id
        self.reserveDocumentID = reserveDocumentID
    }

    static func working(id: String, title: String, document: Document,
                        selection: SelectionState = .empty,
                        selectedLayerIDs: [UUID] = []) -> WorkingDocument {
        WorkingDocument(id: id, title: title, base: document, document: document,
                        baseSelection: selection, selection: selection,
                        baseSelectedLayerIDs: selectedLayerIDs, selectedLayerIDs: selectedLayerIDs,
                        isNew: false)
    }

    func registerImage(_ image: CGImage, id: String? = nil) -> String {
        let key = id ?? "img\(nextImageNumber)"
        nextImageNumber += 1
        images[key] = image
        return key
    }

    var touchedDocuments: [WorkingDocument] { documents.filter(\.isTouched) }

    // MARK: - Dispatch

    /// Performs one operation. `op` names it; the rest are its arguments.
    /// Returns a JSON-compatible value.
    func perform(_ args: [String: Any]) throws -> Any {
        let result = try dispatch(args)
        try checkLayerBudget()
        return result
    }

    /// The most layers one script may add to a document. A model that hits
    /// this is almost always faking something a single layer can do (a
    /// gradient out of a hundred one-pixel strips); the error says so.
    static let maxAddedLayersPerScript = 200

    private func checkLayerBudget() throws {
        for wd in documents {
            let added = wd.document.layers.count - (wd.isNew ? 0 : wd.base.layers.count)
            if added > Self.maxAddedLayersPerScript {
                throw ScriptError("This script has added more than \(Self.maxAddedLayersPerScript) layers to \(wd.id). That usually means it is building something one layer can hold — use fill, fillGradient, addShape or addText on a single layer instead, or ask the user first.")
            }
        }
    }

    private func dispatch(_ args: [String: Any]) throws -> Any {
        guard let op = args["op"] as? String else { throw ScriptError("Missing op") }
        switch op {
        // Session
        case "documents": return documents.map(summary)
        case "activeDocument": return activeID ?? NSNull()
        case "newDocument": return try newDocument(args)
        case "loadImage": return try loadImage(args)
        // Document
        case "state": return try state(args)
        case "describe": return try describe(args)
        case "resizeCanvas": return try resizeCanvas(args)
        case "crop": return try crop(args)
        case "scaleImage": return try scaleImage(args)
        case "fitCanvasToContent": return try fitCanvasToContent(args)
        case "addTextLayer": return try addTextLayer(args)
        case "addShapeLayer": return try addShapeLayer(args)
        case "addLayer": return try addLayer(args)
        case "addImageLayer": return try addImageLayer(args)
        case "group": return try group(args)
        case "ungroup": return try ungroup(args)
        case "setGroup": return try setGroup(args)
        case "deleteGroup": return try deleteGroup(args)
        case "arrange": return try arrange(args)
        case "align": return try align(args)
        case "distribute": return try distribute(args)
        case "select": return try select(args)
        case "selectAll": return try selectAll(args)
        case "deselect": return try deselect(args)
        case "invertSelection": return try invertSelection(args)
        case "setSelectedLayers": return try setSelectedLayers(args)
        case "copyLayers": return try copyLayers(args)
        // Layer
        case "setLayer": return try setLayer(args)
        case "setFrame": return try setFrame(args)
        case "move": return try move(args)
        case "rotate": return try rotate(args)
        case "flip": return try flip(args)
        case "duplicate": return try duplicate(args)
        case "delete": return try delete(args)
        case "reorder": return try reorder(args)
        case "setText": return try setText(args)
        case "setShape": return try setShape(args)
        case "addMask": return try addMask(args)
        case "removeMask": return try removeMask(args)
        case "fill": return try fill(args)
        case "fillGradient": return try fillGradient(args)
        case "draw": return try draw(args)
        case "measureText":
            return ["width": ScriptDrawing.measureText(string(args, "text") ?? "",
                                                       font: string(args, "font") ?? "10px sans-serif")]
        default:
            throw ScriptError("Unknown operation \"\(op)\"")
        }
    }

    // MARK: - Argument helpers

    private func index(of docID: String) throws -> Int {
        guard let i = documents.firstIndex(where: { $0.id == docID }) else {
            throw ScriptError("No open document \"\(docID)\"; use dezzy.documents to list them")
        }
        return i
    }

    private func docIndex(_ args: [String: Any]) throws -> Int {
        guard let id = args["doc"] as? String else { throw ScriptError("Missing document") }
        return try index(of: id)
    }

    private func number(_ args: [String: Any], _ key: String) -> CGFloat? {
        guard let n = args[key] as? NSNumber else { return nil }
        let v = CGFloat(n.doubleValue)
        return v.isFinite ? v : nil
    }

    private func required(_ args: [String: Any], _ key: String) throws -> CGFloat {
        guard let v = number(args, key) else { throw ScriptError("Missing or non-numeric \"\(key)\"") }
        return v
    }

    private func string(_ args: [String: Any], _ key: String) -> String? {
        args[key] as? String
    }

    private func bool(_ args: [String: Any], _ key: String) -> Bool? {
        (args[key] as? NSNumber)?.boolValue
    }

    /// Resolves a layer reference: a short id, else an exact name, else a
    /// case-insensitive name. Topmost wins among duplicate names.
    private func layerID(_ ref: Any?, in wd: WorkingDocument) throws -> UUID {
        guard let ref = ref as? String, !ref.isEmpty else { throw ScriptError("Missing layer") }
        let ids = wd.ids
        if let id = ids.layers[ref] { return id }
        if let layer = wd.document.layers.last(where: { $0.name == ref }) { return layer.id }
        if let layer = wd.document.layers.last(where: { $0.name.lowercased() == ref.lowercased() }) {
            return layer.id
        }
        throw ScriptError("No layer \"\(ref)\" in \(wd.id); layer ids and names are in dezzy.doc(\"\(wd.id)\").layers")
    }

    private func layerIDs(_ refs: Any?, in wd: WorkingDocument) throws -> [UUID] {
        guard let refs = refs as? [Any] else { throw ScriptError("Expected an array of layers") }
        return try refs.map { try layerID($0, in: wd) }
    }

    private func groupID(_ ref: Any?, in wd: WorkingDocument) throws -> UUID {
        guard let ref = ref as? String, !ref.isEmpty else { throw ScriptError("Missing group") }
        if let id = wd.ids.groups[ref] { return id }
        if let group = wd.document.groups.last(where: { $0.name == ref }) { return group.id }
        throw ScriptError("No group \"\(ref)\" in \(wd.id)")
    }

    private func layer(_ id: UUID, in wd: WorkingDocument) throws -> Layer {
        guard let layer = wd.document[layerID: id] else { throw ScriptError("Layer no longer exists") }
        return layer
    }

    private func mutate(_ i: Int, _ body: (inout Document) throws -> Void) rethrows {
        try body(&documents[i].document)
    }

    private func replace(_ layer: Layer, in i: Int) {
        documents[i].document = documents[i].document.replacingLayer(layer)
    }

    private func topLeftRect(_ args: [String: Any], in wd: WorkingDocument) throws -> CGRect {
        CGRect(x: try required(args, "x"), y: try required(args, "y"),
               width: try required(args, "width"), height: try required(args, "height"))
    }

    private func canvasRect(_ args: [String: Any], in wd: WorkingDocument) throws -> CGRect {
        ScriptGeometry.canvas(try topLeftRect(args, in: wd), canvasHeight: wd.document.canvasSize.height)
    }

    private static let ok: [String: Any] = ["ok": true]

    // MARK: - Session ops

    private func summary(_ wd: WorkingDocument) -> [String: Any] {
        ["id": wd.id, "title": wd.title,
         "width": Int(wd.document.canvasSize.width), "height": Int(wd.document.canvasSize.height),
         "layerCount": wd.document.layers.count, "active": wd.id == activeID]
    }

    private func newDocument(_ args: [String: Any]) throws -> Any {
        let size = Document.clampedCanvasSize(CGSize(width: try required(args, "width"),
                                                     height: try required(args, "height")))
        let id = reserveDocumentID()
        let title = string(args, "name") ?? "Untitled"
        let doc = Document(canvasSize: size)
        documents.append(WorkingDocument(id: id, title: title, base: doc, document: doc,
                                         baseSelection: .empty, selection: .empty,
                                         baseSelectedLayerIDs: [], selectedLayerIDs: [],
                                         isNew: true))
        return ["id": id]
    }

    private func loadImage(_ args: [String: Any]) throws -> Any {
        guard let path = string(args, "path"), !path.isEmpty else { throw ScriptError("Missing path") }
        let url = URL(fileURLWithPath: (path as NSString).expandingTildeInPath)
        let image: CGImage
        do {
            image = try ImageImporter.importImage(at: url)
        } catch {
            throw ScriptError("Could not load \(url.path): \(error.localizedDescription)")
        }
        let id = registerImage(image)
        return ["image": id, "width": image.width, "height": image.height]
    }

    // MARK: - Document ops

    private func state(_ args: [String: Any]) throws -> Any {
        let wd = documents[try docIndex(args)]
        return ScriptState.document(id: wd.id, title: wd.title, document: wd.document,
                                    selection: wd.selection, selectedLayerIDs: wd.selectedLayerIDs,
                                    ids: wd.ids)
    }

    private func describe(_ args: [String: Any]) throws -> Any {
        let wd = documents[try docIndex(args)]
        return Self.describe(wd)
    }

    static func describe(_ wd: WorkingDocument) -> String {
        ScriptState.describe(id: wd.id, title: wd.title, document: wd.document,
                             selection: wd.selection, selectedLayerIDs: wd.selectedLayerIDs,
                             ids: wd.ids)
    }

    private func resizeCanvas(_ args: [String: Any]) throws -> Any {
        let i = try docIndex(args)
        let current = documents[i].document.canvasSize
        let size = Document.clampedCanvasSize(CGSize(width: number(args, "width") ?? current.width,
                                                     height: number(args, "height") ?? current.height))
        let anchor = try ScriptGeometry.anchor(named: string(args, "anchor") ?? "center")
        let before = documents[i].document
        documents[i].document = before.resizingCanvas(to: size, anchor: anchor)
        shiftSelection(i, from: before)
        return Self.ok
    }

    private func crop(_ args: [String: Any]) throws -> Any {
        let i = try docIndex(args)
        let rect = try canvasRect(args, in: documents[i]).standardized.integral
        guard rect.width >= 1, rect.height >= 1 else { throw ScriptError("Crop rect must be at least 1×1") }
        let before = documents[i].document
        documents[i].document = before.cropped(to: rect)
        shiftSelection(i, from: before)
        return Self.ok
    }

    /// Crop-shaped ops move the canvas origin; the selection rides along.
    private func shiftSelection(_ i: Int, from before: Document) {
        guard !documents[i].selection.isEmpty else { return }
        // Recover the shift from the first layer's transform (crop only
        // translates), else from the size change assuming a top-left anchor.
        let shift: CGPoint
        if let old = before.layers.first, let new = documents[i].document.layers.first {
            shift = CGPoint(x: new.transform.tx - old.transform.tx, y: new.transform.ty - old.transform.ty)
        } else {
            shift = .zero
        }
        documents[i].selection = documents[i].selection
            .transformed(by: CGAffineTransform(translationX: shift.x, y: shift.y))
    }

    private func scaleImage(_ args: [String: Any]) throws -> Any {
        let i = try docIndex(args)
        let current = documents[i].document.canvasSize
        var width = number(args, "width")
        var height = number(args, "height")
        guard width != nil || height != nil else { throw ScriptError("Give a width, a height, or both") }
        if width == nil { width = current.width * (height! / current.height) }
        if height == nil { height = current.height * (width! / current.width) }
        let size = Document.clampedCanvasSize(CGSize(width: width!, height: height!))
        documents[i].document = documents[i].document.scaled(to: size)
        documents[i].selection = .empty
        return Self.ok
    }

    private func fitCanvasToContent(_ args: [String: Any]) throws -> Any {
        let i = try docIndex(args)
        let before = documents[i].document
        documents[i].document = before.fittingCanvasToContent(padding: number(args, "padding") ?? 0)
        shiftSelection(i, from: before)
        return Self.ok
    }

    private func insert(_ layer: Layer, into i: Int, args: [String: Any]) throws -> Any {
        let above = try args["above"].map { try layerID($0, in: documents[i]) }
        documents[i].document = documents[i].document.insertingLayer(layer, above: above)
        documents[i].selectedLayerIDs = [layer.id]
        return ["id": documents[i].ids.short(layer.id)]
    }

    private func addTextLayer(_ args: [String: Any]) throws -> Any {
        let i = try docIndex(args)
        var spec = TextSpec()
        spec.text = string(args, "text") ?? ""
        guard !spec.text.isEmpty else { throw ScriptError("Text layers need text") }
        if let font = string(args, "fontName") { spec.fontName = font }
        if let size = number(args, "fontSize") { spec.fontSize = Double(size) }
        if let color = args["color"] { spec.color = try ScriptGeometry.color(from: color) }
        guard let image = VectorRasterizer.render(text: spec) else {
            throw ScriptError("Could not render the text")
        }
        let height = documents[i].document.canvasSize.height
        let topLeft = ScriptGeometry.canvas(CGPoint(x: number(args, "x") ?? 0, y: number(args, "y") ?? 0),
                                            canvasHeight: height)
        let transform = CGAffineTransform(translationX: topLeft.x.rounded(),
                                          y: (topLeft.y - CGFloat(image.height)).rounded())
        let layer = Layer(name: string(args, "name") ?? Self.layerName(forText: spec.text),
                          source: image, transform: transform, kind: .text(spec))
        return try insert(layer, into: i, args: args)
    }

    static func layerName(forText text: String) -> String {
        let firstLine = text.split(separator: "\n").first.map(String.init) ?? "Text"
        return firstLine.count > 24 ? String(firstLine.prefix(24)) + "…" : firstLine
    }

    private func shapeStyle(_ args: [String: Any], base: ShapeSpec = ShapeSpec()) throws -> ShapeSpec {
        var spec = base
        if let kind = string(args, "kind") {
            guard let k = ShapeSpec.Kind(rawValue: kind) else {
                throw ScriptError("Unknown shape kind \"\(kind)\"; use rectangle, ellipse or line")
            }
            spec.kind = k
        }
        if args.keys.contains("fill") {
            spec.fill = args["fill"] is NSNull ? nil : try ScriptGeometry.color(from: args["fill"]!)
            if spec.fill?.a == 0 { spec.fill = nil }
        }
        if args.keys.contains("stroke") {
            spec.stroke = args["stroke"] is NSNull ? nil : try ScriptGeometry.color(from: args["stroke"]!)
            if spec.stroke?.a == 0 { spec.stroke = nil }
        }
        if let width = number(args, "strokeWidth") { spec.strokeWidth = Double(max(0, width)) }
        if let style = string(args, "strokeStyle") {
            guard let s = ShapeSpec.StrokeStyle(rawValue: style) else {
                throw ScriptError("Unknown stroke style \"\(style)\"; use solid, dashed or dotted")
            }
            spec.strokeStyle = s
        }
        if let a = bool(args, "arrowStart") { spec.arrowStart = a }
        if let a = bool(args, "arrowEnd") { spec.arrowEnd = a }
        return spec
    }

    private func addShapeLayer(_ args: [String: Any]) throws -> Any {
        let i = try docIndex(args)
        let height = documents[i].document.canvasSize.height
        let style = try shapeStyle(args)
        let spec: ShapeSpec
        let origin: CGPoint
        if style.kind == .line {
            let from = ScriptGeometry.canvas(CGPoint(x: try required(args, "x1"), y: try required(args, "y1")),
                                             canvasHeight: height)
            let to = ScriptGeometry.canvas(CGPoint(x: try required(args, "x2"), y: try required(args, "y2")),
                                           canvasHeight: height)
            (spec, origin) = VectorRasterizer.shapeSpec(from: .zero, lineFrom: from, lineTo: to, style: style)
        } else {
            let rect = try canvasRect(args, in: documents[i])
            (spec, origin) = VectorRasterizer.shapeSpec(from: rect, lineFrom: nil, lineTo: nil, style: style)
        }
        guard let image = VectorRasterizer.render(shape: spec) else {
            throw ScriptError("Could not render the shape")
        }
        let layer = Layer(name: string(args, "name") ?? spec.kind.displayName, source: image,
                          transform: CGAffineTransform(translationX: origin.x.rounded(), y: origin.y.rounded()),
                          kind: .shape(spec))
        return try insert(layer, into: i, args: args)
    }

    /// A paint layer: transparent and canvas-sized by default, or a solid
    /// colour block at the given frame.
    private func addLayer(_ args: [String: Any]) throws -> Any {
        let i = try docIndex(args)
        let canvas = documents[i].document.canvasSize
        let color = try args["color"].map { try ScriptGeometry.color(from: $0) }
        let hasFrame = args["width"] != nil || args["height"] != nil || args["x"] != nil || args["y"] != nil
        let name = string(args, "name") ?? "Layer \(documents[i].document.layers.filter(\.isPaintable).count + 1)"
        if color == nil, !hasFrame {
            guard let layer = DocumentStore.blankPaintLayer(canvasSize: canvas, name: name) else {
                throw ScriptError("Could not create the layer")
            }
            return try insert(layer, into: i, args: args)
        }
        let frame = CGRect(x: number(args, "x") ?? 0, y: number(args, "y") ?? 0,
                           width: number(args, "width") ?? canvas.width,
                           height: number(args, "height") ?? canvas.height).standardized
        guard frame.width >= 1, frame.height >= 1 else { throw ScriptError("Layer size must be at least 1×1") }
        guard let image = Self.solidImage(width: Int(frame.width.rounded()), height: Int(frame.height.rounded()),
                                          color: color ?? ColorSpec(r: 0, g: 0, b: 0, a: 0)) else {
            throw ScriptError("Could not create the layer")
        }
        let canvasFrame = ScriptGeometry.canvas(frame, canvasHeight: canvas.height)
        let layer = Layer(name: name, source: image,
                          transform: CGAffineTransform(translationX: canvasFrame.minX.rounded(),
                                                       y: canvasFrame.minY.rounded()),
                          isPaintable: true)
        return try insert(layer, into: i, args: args)
    }

    static func solidImage(width: Int, height: Int, color: ColorSpec) -> CGImage? {
        guard width >= 1, height >= 1,
              let ctx = CGContext(data: nil, width: width, height: height,
                                  bitsPerComponent: 8, bytesPerRow: 0,
                                  space: DezzyColorSpace.displayP3,
                                  bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue) else { return nil }
        if color.a > 0 {
            ctx.setFillColor(color.cgColor)
            ctx.fill(CGRect(x: 0, y: 0, width: width, height: height))
        }
        return ctx.makeImage()
    }

    /// Places a registered image. Default placement mirrors File ▸ Place:
    /// centred, scaled down to fit the canvas. `x`/`y` pin the top-left;
    /// `width`/`height` fit the image inside that box (aspect kept) unless
    /// `stretch` is true.
    private func addImageLayer(_ args: [String: Any]) throws -> Any {
        let i = try docIndex(args)
        guard let ref = string(args, "image") else { throw ScriptError("Missing image") }
        guard let image = images[ref] else {
            throw ScriptError("No image \"\(ref)\"; images come from dezzy.loadImage(path) or the generate tool")
        }
        let canvas = documents[i].document.canvasSize
        let name = string(args, "name") ?? ref
        var layer = DocumentStore.placedLayer(image, named: name, canvasSize: canvas)
        let x = number(args, "x"), y = number(args, "y")
        let w = number(args, "width"), h = number(args, "height")
        if x != nil || y != nil || w != nil || h != nil {
            let current = ScriptGeometry.topLeft(layer.canvasBounds, canvasHeight: canvas.height)
            var size = CGSize(width: image.width, height: image.height)
            if w != nil || h != nil {
                if bool(args, "stretch") == true, let w, let h {
                    size = CGSize(width: w, height: h)
                } else {
                    let box = CGSize(width: w ?? .greatestFiniteMagnitude, height: h ?? .greatestFiniteMagnitude)
                    let scale = min(box.width / size.width, box.height / size.height)
                    size = CGSize(width: size.width * scale, height: size.height * scale)
                }
            }
            let frame = CGRect(x: x ?? current.minX, y: y ?? current.minY,
                               width: size.width, height: size.height)
            layer.transform = ScriptGeometry.transform(fitting: layer.sourceSize,
                                                       to: ScriptGeometry.canvas(frame, canvasHeight: canvas.height))
        }
        return try insert(layer, into: i, args: args)
    }

    private func group(_ args: [String: Any]) throws -> Any {
        let i = try docIndex(args)
        let ids = try layerIDs(args["layers"], in: documents[i])
        guard !ids.isEmpty else { throw ScriptError("Group needs at least one layer") }
        let name = string(args, "name") ?? documents[i].document.nextGroupName()
        guard let (doc, groupID) = documents[i].document.addingGroup(named: name, aroundLayers: ids) else {
            throw ScriptError("Could not group those layers")
        }
        documents[i].document = doc
        return ["id": documents[i].ids.short(groupID)]
    }

    private func ungroup(_ args: [String: Any]) throws -> Any {
        let i = try docIndex(args)
        let id = try groupID(args["group"], in: documents[i])
        documents[i].document = documents[i].document.ungrouping(id)
        return Self.ok
    }

    private func setGroup(_ args: [String: Any]) throws -> Any {
        let i = try docIndex(args)
        let id = try groupID(args["group"], in: documents[i])
        guard let index = documents[i].document.groupIndex(of: id) else { throw ScriptError("Group no longer exists") }
        var group = documents[i].document.groups[index]
        if let name = string(args, "name") { group.name = name }
        if let visible = bool(args, "visible") { group.isVisible = visible }
        if let opacity = number(args, "opacity") { group.opacity = Float(min(max(opacity, 0), 1)) }
        if args.keys.contains("blendMode") {
            if let mode = string(args, "blendMode"), mode != "pass-through" {
                group.blendMode = try ScriptGeometry.blendMode(named: mode)
            } else {
                group.blendMode = nil
            }
        }
        documents[i].document.groups[index] = group
        return Self.ok
    }

    private func deleteGroup(_ args: [String: Any]) throws -> Any {
        let i = try docIndex(args)
        let id = try groupID(args["group"], in: documents[i])
        documents[i].document = documents[i].document.removingGroup(id)
        pruneSelectedLayers(i)
        return Self.ok
    }

    private func pruneSelectedLayers(_ i: Int) {
        let live = Set(documents[i].document.layers.map(\.id))
        documents[i].selectedLayerIDs.removeAll { !live.contains($0) }
    }

    private func arrange(_ args: [String: Any]) throws -> Any {
        let i = try docIndex(args)
        let ids = try layerIDs(args["layers"], in: documents[i])
        let direction = ArrangeDirection(rawValue: string(args, "direction") ?? "horizontal")
        guard let direction else { throw ScriptError("direction must be \"horizontal\" or \"vertical\"") }
        let alignment: ArrangeAlignment
        switch (string(args, "align") ?? "start").lowercased() {
        case "start", "top", "left": alignment = .start
        case "center", "centre", "middle": alignment = .center
        case "end", "bottom", "right": alignment = .end
        default: throw ScriptError("align must be start, center or end (top/bottom, left/right also work)")
        }
        let height = documents[i].document.canvasSize.height
        var origin: CGPoint?
        if let x = number(args, "x"), let y = number(args, "y") {
            origin = ScriptGeometry.canvas(CGPoint(x: x, y: y), canvasHeight: height)
        } else if number(args, "x") != nil || number(args, "y") != nil {
            throw ScriptError("Give both x and y, or neither")
        }
        documents[i].document = documents[i].document.arranging(ids, direction: direction,
                                                                gap: number(args, "gap") ?? 0,
                                                                alignment: alignment, origin: origin)
        return Self.ok
    }

    private func align(_ args: [String: Any]) throws -> Any {
        let i = try docIndex(args)
        let ids = try layerIDs(args["layers"], in: documents[i])
        let edge: AlignEdge
        switch (string(args, "edge") ?? "").lowercased() {
        case "left": edge = .left
        case "right": edge = .right
        case "top": edge = .top
        case "bottom": edge = .bottom
        case "centerx", "center-x", "horizontal-center", "hcenter": edge = .centerH
        case "centery", "center-y", "vertical-center", "vcenter": edge = .centerV
        default: throw ScriptError("edge must be left, centerX, right, top, centerY or bottom")
        }
        let reference: AlignReference
        switch (string(args, "to") ?? "canvas").lowercased() {
        case "canvas": reference = .canvas
        case "selection", "bounds", "each-other": reference = .selectionBounds
        default: throw ScriptError("to must be \"canvas\" or \"selection\"")
        }
        documents[i].document = documents[i].document.aligning(ids.map { .layer($0) }, to: edge,
                                                               reference: reference)
        return Self.ok
    }

    private func distribute(_ args: [String: Any]) throws -> Any {
        let i = try docIndex(args)
        let ids = try layerIDs(args["layers"], in: documents[i])
        guard let axis = AlignAxis(rawValue: string(args, "axis") ?? "horizontal") else {
            throw ScriptError("axis must be \"horizontal\" or \"vertical\"")
        }
        let mode: DistributeMode
        switch (string(args, "mode") ?? "spacing").lowercased() {
        case "spacing", "gaps": mode = .spacing
        case "centers", "centres": mode = .centers
        default: throw ScriptError("mode must be \"spacing\" or \"centers\"")
        }
        guard ids.count >= 3 else { throw ScriptError("Distribute needs at least three layers") }
        documents[i].document = documents[i].document.distributing(ids.map { .layer($0) }, along: axis, mode: mode)
        return Self.ok
    }

    private func select(_ args: [String: Any]) throws -> Any {
        let i = try docIndex(args)
        let rect = try canvasRect(args, in: documents[i]).standardized
        guard rect.width > 0, rect.height > 0 else { throw ScriptError("Selection rect must have positive size") }
        documents[i].selection = SelectionState(path: CGPath(rect: rect, transform: nil))
        return Self.ok
    }

    private func selectAll(_ args: [String: Any]) throws -> Any {
        let i = try docIndex(args)
        documents[i].selection = SelectionState(path: CGPath(rect: documents[i].document.canvasRect, transform: nil))
        return Self.ok
    }

    private func deselect(_ args: [String: Any]) throws -> Any {
        let i = try docIndex(args)
        documents[i].selection = .empty
        return Self.ok
    }

    private func invertSelection(_ args: [String: Any]) throws -> Any {
        let i = try docIndex(args)
        documents[i].selection = documents[i].selection.inverted(in: documents[i].document.canvasRect)
        return Self.ok
    }

    private func setSelectedLayers(_ args: [String: Any]) throws -> Any {
        let i = try docIndex(args)
        documents[i].selectedLayerIDs = try layerIDs(args["layers"], in: documents[i])
        return Self.ok
    }

    /// Copies layers into another document, on top of its stack. Canvas
    /// positions are kept unless `x`/`y` place the copies' union top-left.
    private func copyLayers(_ args: [String: Any]) throws -> Any {
        let from = try docIndex(args)
        guard let toID = string(args, "to") else { throw ScriptError("Missing destination document") }
        let to = try index(of: toID)
        let ids = try layerIDs(args["layers"], in: documents[from])
        let sourceHeight = documents[from].document.canvasSize.height
        let targetHeight = documents[to].document.canvasSize.height
        var copies: [Layer] = []
        var union = CGRect.null
        for id in ids {
            let original = try layer(id, in: documents[from])
            var copy = original.duplicated(name: original.name)
            copy.groupID = nil
            copy.isClippedToBelow = false
            // Keep the top-left position across differently sized canvases.
            let tl = ScriptGeometry.topLeft(original.canvasBounds, canvasHeight: sourceHeight)
            let target = ScriptGeometry.canvas(tl, canvasHeight: targetHeight)
            copy.transform = original.transform.concatenating(
                CGAffineTransform(translationX: target.minX - original.canvasBounds.minX,
                                  y: target.minY - original.canvasBounds.minY))
            union = union.union(copy.canvasBounds)
            copies.append(copy)
        }
        if let x = number(args, "x"), let y = number(args, "y"), !union.isNull {
            let wanted = ScriptGeometry.canvas(CGPoint(x: x, y: y), canvasHeight: targetHeight)
            let delta = CGPoint(x: wanted.x - union.minX, y: wanted.y - union.maxY)
            for k in copies.indices {
                copies[k].transform = copies[k].transform.concatenating(
                    CGAffineTransform(translationX: delta.x, y: delta.y))
            }
        }
        for copy in copies {
            documents[to].document = documents[to].document.insertingLayer(copy, above: nil)
        }
        documents[to].selectedLayerIDs = copies.map(\.id)
        let ids2 = documents[to].ids
        return copies.map { ids2.short($0.id) }
    }

    // MARK: - Layer ops

    private func setLayer(_ args: [String: Any]) throws -> Any {
        let i = try docIndex(args)
        var layer = try layer(try layerID(args["layer"], in: documents[i]), in: documents[i])
        if let name = string(args, "name") { layer.name = name }
        if let visible = bool(args, "visible") { layer.isVisible = visible }
        if let opacity = number(args, "opacity") { layer.opacity = Float(min(max(opacity, 0), 1)) }
        if let mode = string(args, "blendMode") { layer.blendMode = try ScriptGeometry.blendMode(named: mode) }
        if let clipped = bool(args, "clipped") { layer.isClippedToBelow = clipped }
        replace(layer, in: i)
        if args["clipped"] != nil { documents[i].document = documents[i].document.normalizingClipping() }
        return Self.ok
    }

    /// Position-only changes translate (rotation and flips survive); a size
    /// change rebuilds the transform axis-aligned.
    private func setFrame(_ args: [String: Any]) throws -> Any {
        let i = try docIndex(args)
        var layer = try layer(try layerID(args["layer"], in: documents[i]), in: documents[i])
        let height = documents[i].document.canvasSize.height
        let current = ScriptGeometry.topLeft(layer.canvasBounds, canvasHeight: height)
        let width = number(args, "width"), h = number(args, "height")
        let frame = CGRect(x: number(args, "x") ?? current.minX, y: number(args, "y") ?? current.minY,
                           width: width ?? current.width, height: h ?? current.height)
        guard frame.width > 0, frame.height > 0 else { throw ScriptError("Frame size must be positive") }
        let canvasFrame = ScriptGeometry.canvas(frame, canvasHeight: height)
        if width == nil, h == nil {
            let delta = CGPoint(x: canvasFrame.minX - layer.canvasBounds.minX,
                                y: canvasFrame.minY - layer.canvasBounds.minY)
            layer.transform = TransformMath.moved(initial: layer.transform, delta: delta)
        } else {
            layer.transform = ScriptGeometry.transform(fitting: layer.sourceSize, to: canvasFrame)
        }
        replace(layer, in: i)
        return Self.ok
    }

    private func move(_ args: [String: Any]) throws -> Any {
        let i = try docIndex(args)
        let id = try layerID(args["layer"], in: documents[i])
        let delta = CGPoint(x: number(args, "dx") ?? 0, y: -(number(args, "dy") ?? 0))
        documents[i].document = documents[i].document.translatingLayers([id], by: delta)
        return Self.ok
    }

    private func rotate(_ args: [String: Any]) throws -> Any {
        let i = try docIndex(args)
        var layer = try layer(try layerID(args["layer"], in: documents[i]), in: documents[i])
        let degrees = try required(args, "degrees")
        let radians = -degrees * .pi / 180  // clockwise in → y-up CCW radians
        layer.transform = ScriptGeometry.transform(layer.transform, sourceRect: layer.sourceRect,
                                                   aboutCenter: CGAffineTransform(rotationAngle: radians))
        replace(layer, in: i)
        return Self.ok
    }

    private func flip(_ args: [String: Any]) throws -> Any {
        let i = try docIndex(args)
        var layer = try layer(try layerID(args["layer"], in: documents[i]), in: documents[i])
        let about: CGAffineTransform
        switch (string(args, "axis") ?? "horizontal").lowercased() {
        case "horizontal", "h", "x": about = CGAffineTransform(scaleX: -1, y: 1)
        case "vertical", "v", "y": about = CGAffineTransform(scaleX: 1, y: -1)
        default: throw ScriptError("axis must be \"horizontal\" or \"vertical\"")
        }
        layer.transform = ScriptGeometry.transform(layer.transform, sourceRect: layer.sourceRect, aboutCenter: about)
        replace(layer, in: i)
        return Self.ok
    }

    private func duplicate(_ args: [String: Any]) throws -> Any {
        let i = try docIndex(args)
        let id = try layerID(args["layer"], in: documents[i])
        let original = try layer(id, in: documents[i])
        let copy = original.duplicated(name: string(args, "name") ?? original.name + " copy")
        guard let index = documents[i].document.layerIndex(of: id) else { throw ScriptError("Layer no longer exists") }
        documents[i].document.layers.insert(copy, at: index + 1)
        documents[i].selectedLayerIDs = [copy.id]
        return ["id": documents[i].ids.short(copy.id)]
    }

    private func delete(_ args: [String: Any]) throws -> Any {
        let i = try docIndex(args)
        let id = try layerID(args["layer"], in: documents[i])
        documents[i].document = documents[i].document.removingLayer(id: id)
        pruneSelectedLayers(i)
        return Self.ok
    }

    /// `to`: "front", "back", "up", "down", or a 0-based index from the
    /// bottom; or `above`/`below` naming another layer. The moved layer
    /// adopts its new neighbour's group.
    private func reorder(_ args: [String: Any]) throws -> Any {
        let i = try docIndex(args)
        let id = try layerID(args["layer"], in: documents[i])
        var doc = documents[i].document
        guard let from = doc.layerIndex(of: id) else { throw ScriptError("Layer no longer exists") }
        var layer = doc.layers.remove(at: from)
        var at: Int
        var neighbourGroup: UUID?
        if let above = args["above"] {
            let anchor = try layerID(above, in: documents[i])
            guard let idx = doc.layerIndex(of: anchor) else { throw ScriptError("Layer no longer exists") }
            at = idx + 1
            neighbourGroup = doc.layers[idx].groupID
        } else if let below = args["below"] {
            let anchor = try layerID(below, in: documents[i])
            guard let idx = doc.layerIndex(of: anchor) else { throw ScriptError("Layer no longer exists") }
            at = idx
            neighbourGroup = doc.layers[idx].groupID
        } else if let n = args["to"] as? NSNumber, !(args["to"] is String) {
            at = min(max(n.intValue, 0), doc.layers.count)
            let neighbour = at < doc.layers.count ? doc.layers[at] : doc.layers.last
            neighbourGroup = neighbour?.groupID
        } else {
            switch (string(args, "to") ?? "").lowercased() {
            case "front", "top": at = doc.layers.count; neighbourGroup = nil
            case "back", "bottom": at = 0; neighbourGroup = nil
            case "up", "forward":
                at = min(from + 1, doc.layers.count)
                neighbourGroup = at > 0 ? doc.layers[at - 1].groupID : nil
            case "down", "backward":
                at = max(from - 1, 0)
                neighbourGroup = at < doc.layers.count ? doc.layers[at].groupID : nil
            default:
                throw ScriptError("to must be front, back, up, down or an index; or use above/below")
            }
        }
        layer.groupID = neighbourGroup
        doc.layers.insert(layer, at: at)
        documents[i].document = doc.normalizingGroups().normalizingClipping()
        return Self.ok
    }

    /// Re-rasterises a text layer from an updated spec, keeping its top-left
    /// (mirrors `DocumentStore.updateVectorLayer`).
    private func setText(_ args: [String: Any]) throws -> Any {
        let i = try docIndex(args)
        let layer = try layer(try layerID(args["layer"], in: documents[i]), in: documents[i])
        guard var spec = layer.kind.textSpec else { throw ScriptError("\"\(layer.name)\" is not a text layer") }
        if let text = string(args, "text") { spec.text = text }
        if let font = string(args, "fontName") { spec.fontName = font }
        if let size = number(args, "fontSize") { spec.fontSize = Double(size) }
        if let color = args["color"] { spec.color = try ScriptGeometry.color(from: color) }
        guard let image = VectorRasterizer.render(text: spec) else { throw ScriptError("Could not render the text") }
        let shift = CGAffineTransform(translationX: 0, y: CGFloat(layer.source.height - image.height))
        replace(Self.rerasterized(layer, image: image, kind: .text(spec), anchorShift: shift), in: i)
        return Self.ok
    }

    /// Re-rasterises a shape layer, keeping its centre.
    private func setShape(_ args: [String: Any]) throws -> Any {
        let i = try docIndex(args)
        let layer = try layer(try layerID(args["layer"], in: documents[i]), in: documents[i])
        guard let current = layer.kind.shapeSpec else { throw ScriptError("\"\(layer.name)\" is not a shape layer") }
        var spec = try shapeStyle(args, base: current)
        if spec.kind == .line, current.kind != .line { throw ScriptError("Use a new line layer instead of changing a shape into a line") }
        if spec.kind != .line, current.kind == .line { throw ScriptError("A line can't become a rectangle or ellipse") }
        // Padding may change with the stroke; keep the drawn geometry's size.
        let inner = CGSize(width: current.size.width - 2 * current.padding,
                           height: current.size.height - 2 * current.padding)
        spec.size = CGSize(width: inner.width + 2 * spec.padding, height: inner.height + 2 * spec.padding)
        if spec.kind == .line {
            let d = CGFloat(spec.padding - current.padding)
            spec.lineStart = CGPoint(x: current.lineStart.x + d, y: current.lineStart.y + d)
            spec.lineEnd = CGPoint(x: current.lineEnd.x + d, y: current.lineEnd.y + d)
        }
        guard let image = VectorRasterizer.render(shape: spec) else { throw ScriptError("Could not render the shape") }
        let shift = CGAffineTransform(translationX: CGFloat(layer.source.width - image.width) / 2,
                                      y: CGFloat(layer.source.height - image.height) / 2)
        replace(Self.rerasterized(layer, image: image, kind: .shape(spec), anchorShift: shift), in: i)
        return Self.ok
    }

    private static func rerasterized(_ layer: Layer, image: CGImage, kind: LayerKind,
                                     anchorShift: CGAffineTransform) -> Layer {
        var out = Layer(id: layer.id, sourceID: UUID(), name: layer.name, source: image,
                        transform: anchorShift.concatenating(layer.transform),
                        opacity: layer.opacity, isVisible: layer.isVisible, mask: nil,
                        isPaintable: false, kind: kind, blendMode: layer.blendMode,
                        isClippedToBelow: layer.isClippedToBelow, groupID: layer.groupID,
                        effects: layer.effects)
        if let mask = layer.mask, mask.texture.width == image.width, mask.texture.height == image.height {
            out.mask = mask
        }
        return out
    }

    private func addMask(_ args: [String: Any]) throws -> Any {
        let i = try docIndex(args)
        var layer = try layer(try layerID(args["layer"], in: documents[i]), in: documents[i])
        let texture: MaskTexture
        switch (string(args, "from") ?? "selection").lowercased() {
        case "selection":
            texture = MaskFactory.maskTexture(for: layer, selection: documents[i].selection, featherCanvasPx: 0)
        case "reveal", "reveal-all", "white":
            texture = MaskTexture(width: layer.source.width, height: layer.source.height, fill: 255)
        case "hide", "hide-all", "black":
            texture = MaskTexture(width: layer.source.width, height: layer.source.height, fill: 0)
        default:
            throw ScriptError("from must be \"selection\", \"reveal\" or \"hide\"")
        }
        layer.mask = Mask(texture: texture, isEnabled: true)
        replace(layer, in: i)
        return Self.ok
    }

    private func removeMask(_ args: [String: Any]) throws -> Any {
        let i = try docIndex(args)
        var layer = try layer(try layerID(args["layer"], in: documents[i]), in: documents[i])
        layer.mask = nil
        replace(layer, in: i)
        return Self.ok
    }

    /// Fills a paint layer's pixels with a colour — inside the selection if
    /// there is one, else the whole layer. Imported images are never painted
    /// (§5): the script is told to add a layer instead.
    private func fill(_ args: [String: Any]) throws -> Any {
        let i = try docIndex(args)
        let layer = try layer(try layerID(args["layer"], in: documents[i]), in: documents[i])
        guard layer.isPaintable else {
            throw ScriptError("\"\(layer.name)\" is an imported image and can't be painted; add a new layer with a colour instead")
        }
        guard let value = args["color"] else { throw ScriptError("Missing colour") }
        let color = try ScriptGeometry.color(from: value)
        let coverage: MaskTexture? = documents[i].selection.isEmpty ? nil
            : MaskFactory.maskTexture(for: layer, selection: documents[i].selection, featherCanvasPx: 0)
        guard let image = Self.filled(layer.source, color: color, coverage: coverage) else {
            throw ScriptError("Could not fill the layer")
        }
        var out = layer
        out = Layer(id: layer.id, sourceID: UUID(), name: layer.name, source: image,
                    transform: layer.transform, opacity: layer.opacity, isVisible: layer.isVisible,
                    mask: layer.mask, isPaintable: true, kind: layer.kind, blendMode: layer.blendMode,
                    isClippedToBelow: layer.isClippedToBelow, groupID: layer.groupID, effects: layer.effects)
        replace(out, in: i)
        return Self.ok
    }

    /// Source pixels with `color` composited where `coverage` says (whole
    /// image when nil). Coverage is source-resolution, row 0 at top, like
    /// every mask buffer (§5b).
    static func filled(_ source: CGImage, color: ColorSpec, coverage: MaskTexture?) -> CGImage? {
        let width = source.width, height = source.height
        guard width >= 1, height >= 1,
              let ctx = CGContext(data: nil, width: width, height: height,
                                  bitsPerComponent: 8, bytesPerRow: 0,
                                  space: DezzyColorSpace.displayP3,
                                  bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue) else { return nil }
        ctx.draw(source, in: CGRect(x: 0, y: 0, width: width, height: height))
        guard let coverage else {
            ctx.setBlendMode(.copy)
            ctx.setFillColor(color.cgColor)
            ctx.fill(CGRect(x: 0, y: 0, width: width, height: height))
            return ctx.makeImage()
        }
        // The fill colour in the layer's own (Display P3) space, premultiplied.
        let p3 = color.cgColor.converted(to: DezzyColorSpace.displayP3, intent: .defaultIntent, options: nil)
        let c = p3?.components ?? [0, 0, 0, 1]
        let fr = Double(c.count > 2 ? c[0] : 0), fg = Double(c.count > 2 ? c[1] : 0)
        let fb = Double(c.count > 2 ? c[2] : 0), fa = Double(c.count > 3 ? c[3] : 1)
        guard let data = ctx.data else { return nil }
        let rowBytes = ctx.bytesPerRow
        let bytes = data.assumingMemoryBound(to: UInt8.self)
        coverage.data.withUnsafeBytes { (raw: UnsafeRawBufferPointer) in
            guard let mask = raw.baseAddress?.assumingMemoryBound(to: UInt8.self),
                  coverage.width == width, coverage.height == height else { return }
            for row in 0..<height {
                // CGContext rows here are also top-first (bitmap origin is
                // the first byte), matching the mask's row order.
                let ctxRow = row
                for col in 0..<width {
                    let k = Double(mask[row * width + col]) / 255
                    guard k > 0 else { continue }
                    let p = ctxRow * rowBytes + col * 4
                    let old = (Double(bytes[p]) / 255, Double(bytes[p + 1]) / 255,
                               Double(bytes[p + 2]) / 255, Double(bytes[p + 3]) / 255)
                    // Selected pixels take the colour (with its own alpha)
                    // at coverage strength: k=1 replaces, k<1 blends.
                    let nr = fr * fa * k + old.0 * (1 - k)
                    let ng = fg * fa * k + old.1 * (1 - k)
                    let nb = fb * fa * k + old.2 * (1 - k)
                    let na = fa * k + old.3 * (1 - k)
                    bytes[p] = UInt8(min(max(nr * 255, 0), 255).rounded())
                    bytes[p + 1] = UInt8(min(max(ng * 255, 0), 255).rounded())
                    bytes[p + 2] = UInt8(min(max(nb * 255, 0), 255).rounded())
                    bytes[p + 3] = UInt8(min(max(na * 255, 0), 255).rounded())
                }
            }
        }
        return ctx.makeImage()
    }

    // MARK: - Change summary

    /// What a script did to a document, for the model: canvas size changes
    /// and layers added / removed / changed by name.
    /// A multi-stop gradient over a paint layer's pixels — inside the
    /// selection if there is one. `from`/`to` are top-left canvas points
    /// (default: the layer's top centre → bottom centre); beyond them the
    /// end colours clamp, as the Gradient tool does. Stops are colours,
    /// optionally with an offset in 0…1; without offsets they space evenly.
    private func fillGradient(_ args: [String: Any]) throws -> Any {
        let i = try docIndex(args)
        let layer = try layer(try layerID(args["layer"], in: documents[i]), in: documents[i])
        guard layer.isPaintable else {
            throw ScriptError("\"\(layer.name)\" is an imported image and can't be painted; add a new layer and fill that instead")
        }
        let canvasHeight = documents[i].document.canvasSize.height
        let frame = ScriptGeometry.topLeft(layer.canvasBounds, canvasHeight: canvasHeight)
        let from = try Self.point(args["from"]) ?? CGPoint(x: frame.midX, y: frame.minY)
        let to = try Self.point(args["to"]) ?? CGPoint(x: frame.midX, y: frame.maxY)
        guard from != to else { throw ScriptError("Gradient start and end must differ") }
        let stops = try Self.gradientStops(args["stops"])
        let shape: GradientShape
        switch (string(args, "shape") ?? "linear").lowercased() {
        case "linear": shape = .linear
        case "radial": shape = .radial
        case let other: throw ScriptError("Unknown gradient shape \"\(other)\"; use \"linear\" or \"radial\"")
        }
        let coverage: MaskTexture? = documents[i].selection.isEmpty ? nil
            : MaskFactory.maskTexture(for: layer, selection: documents[i].selection, featherCanvasPx: 0)
        guard let image = Self.gradiented(layer,
                                          start: ScriptGeometry.canvas(from, canvasHeight: canvasHeight),
                                          end: ScriptGeometry.canvas(to, canvasHeight: canvasHeight),
                                          shape: shape, colors: stops.map(\.color), locations: stops.map(\.offset),
                                          coverage: coverage) else {
            throw ScriptError("Could not draw the gradient")
        }
        let out = Layer(id: layer.id, sourceID: UUID(), name: layer.name, source: image,
                        transform: layer.transform, opacity: layer.opacity, isVisible: layer.isVisible,
                        mask: layer.mask, isPaintable: true, kind: layer.kind, blendMode: layer.blendMode,
                        isClippedToBelow: layer.isClippedToBelow, groupID: layer.groupID, effects: layer.effects)
        replace(out, in: i)
        return Self.ok
    }

    /// Replays recorded Canvas-2D commands into a paint layer's pixels
    /// (`ScriptDrawing`), inside the selection if there is one.
    private func draw(_ args: [String: Any]) throws -> Any {
        let i = try docIndex(args)
        let layer = try layer(try layerID(args["layer"], in: documents[i]), in: documents[i])
        guard layer.isPaintable else {
            throw ScriptError("\"\(layer.name)\" is an imported image and can't be painted; add a new layer and draw on that instead")
        }
        let commands = (args["commands"] as? [Any] ?? []).compactMap { $0 as? [Any] }
        guard !commands.isEmpty else { return Self.ok }
        let coverage: MaskTexture? = documents[i].selection.isEmpty ? nil
            : MaskFactory.maskTexture(for: layer, selection: documents[i].selection, featherCanvasPx: 0)
        guard let image = try ScriptDrawing.render(layer, commands: commands,
                                                   canvasHeight: documents[i].document.canvasSize.height,
                                                   coverage: coverage) else {
            throw ScriptError("Could not draw on the layer")
        }
        let out = Layer(id: layer.id, sourceID: UUID(), name: layer.name, source: image,
                        transform: layer.transform, opacity: layer.opacity, isVisible: layer.isVisible,
                        mask: layer.mask, isPaintable: true, kind: layer.kind, blendMode: layer.blendMode,
                        isClippedToBelow: layer.isClippedToBelow, groupID: layer.groupID, effects: layer.effects)
        replace(out, in: i)
        return Self.ok
    }

    /// `[x, y]` or `{x, y}`; nil when absent.
    static func point(_ value: Any?) throws -> CGPoint? {
        guard let value else { return nil }
        if let pair = value as? [Any], pair.count == 2,
           let x = (pair[0] as? NSNumber)?.doubleValue, let y = (pair[1] as? NSNumber)?.doubleValue {
            return CGPoint(x: x, y: y)
        }
        if let dict = value as? [String: Any],
           let x = (dict["x"] as? NSNumber)?.doubleValue, let y = (dict["y"] as? NSNumber)?.doubleValue {
            return CGPoint(x: x, y: y)
        }
        throw ScriptError("A point is [x, y] or {x, y}")
    }

    /// Colours (evenly spaced) or `{offset, color}` objects, sorted by offset.
    static func gradientStops(_ value: Any?) throws -> [(offset: CGFloat, color: CGColor)] {
        guard let list = value as? [Any], list.count >= 2 else {
            throw ScriptError("stops needs at least two colours, like [\"#ff0000\", \"#0000ff\"] or [{offset: 0, color: \"red\"}, …]")
        }
        var stops: [(offset: CGFloat, color: CGColor)] = []
        for (n, entry) in list.enumerated() {
            let even = CGFloat(n) / CGFloat(list.count - 1)
            if let dict = entry as? [String: Any], let raw = dict["color"] ?? dict["colour"] {
                let offset = (dict["offset"] ?? dict["position"] ?? dict["at"]).flatMap { ($0 as? NSNumber)?.doubleValue }
                stops.append((min(max(CGFloat(offset ?? Double(even)), 0), 1), try ScriptGeometry.color(from: raw).cgColor))
            } else {
                stops.append((even, try ScriptGeometry.color(from: entry).cgColor))
            }
        }
        return stops.sorted { $0.offset < $1.offset }
    }

    /// The gradient drawn into a copy of the layer's pixels through Core
    /// Graphics, clipped to `coverage` (source space) when the selection
    /// has one. Mirrors `DocumentStore.pixelsGradiented`, with N stops.
    static func gradiented(_ layer: Layer, start: CGPoint, end: CGPoint, shape: GradientShape,
                           colors: [CGColor], locations: [CGFloat], coverage: MaskTexture?) -> CGImage? {
        let width = layer.source.width, height = layer.source.height
        guard width >= 1, height >= 1, layer.transform.isInvertible,
              let ctx = CGContext(data: nil, width: width, height: height,
                                  bitsPerComponent: 8, bytesPerRow: 0,
                                  space: DezzyColorSpace.displayP3,
                                  bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue) else { return nil }
        ctx.draw(layer.source, in: layer.sourceRect)
        if let coverage, coverage.width == width, coverage.height == height, let mask = coverage.cgImage {
            ctx.clip(to: layer.sourceRect, mask: mask)
        }
        ctx.concatenate(layer.transform.inverted())
        let srgb = colors.map { $0.converted(to: DezzyColorSpace.sRGB, intent: .defaultIntent, options: nil) ?? $0 }
        guard let gradient = CGGradient(colorsSpace: DezzyColorSpace.sRGB, colors: srgb as CFArray,
                                        locations: locations) else { return nil }
        let options: CGGradientDrawingOptions = [.drawsBeforeStartLocation, .drawsAfterEndLocation]
        switch shape {
        case .linear:
            ctx.drawLinearGradient(gradient, start: start, end: end, options: options)
        case .radial:
            ctx.drawRadialGradient(gradient, startCenter: start, startRadius: 0, endCenter: start,
                                   endRadius: hypot(end.x - start.x, end.y - start.y), options: options)
        }
        return ctx.makeImage()
    }

    static func changeSummary(_ wd: WorkingDocument) -> String {
        var parts: [String] = []
        if wd.isNew {
            parts.append("created \(Int(wd.document.canvasSize.width))×\(Int(wd.document.canvasSize.height))")
        } else if wd.base.canvasSize != wd.document.canvasSize {
            parts.append("canvas \(Int(wd.base.canvasSize.width))×\(Int(wd.base.canvasSize.height)) → \(Int(wd.document.canvasSize.width))×\(Int(wd.document.canvasSize.height))")
        }
        let baseByID = Dictionary(wd.base.layers.map { ($0.id, $0) }, uniquingKeysWith: { a, _ in a })
        let newByID = Dictionary(wd.document.layers.map { ($0.id, $0) }, uniquingKeysWith: { a, _ in a })
        let added = wd.document.layers.filter { baseByID[$0.id] == nil }.map(\.name)
        let removed = wd.base.layers.filter { newByID[$0.id] == nil }.map(\.name)
        let changed = wd.document.layers.filter { layer in
            guard let old = baseByID[layer.id] else { return false }
            return old != layer
        }.map(\.name)
        if !added.isEmpty { parts.append("added \(nameList(added))") }
        if !removed.isEmpty { parts.append("removed \(nameList(removed))") }
        if !changed.isEmpty { parts.append("changed \(nameList(changed))") }
        if wd.base.layers.map(\.id) != wd.document.layers.map(\.id), added.isEmpty, removed.isEmpty {
            parts.append("reordered layers")
        }
        if wd.selection != wd.baseSelection { parts.append("selection changed") }
        if parts.isEmpty { parts.append("no visible change") }
        return parts.joined(separator: "; ")
    }

    /// Quoted names, or a count with the most common names once the list
    /// would drown the result ("108 layers: \"Rectangle\" ×108").
    static func nameList(_ names: [String]) -> String {
        if names.count <= 8 { return names.map { "\"\($0)\"" }.joined(separator: ", ") }
        var counts: [String: Int] = [:]
        for name in names { counts[name, default: 0] += 1 }
        let top = counts.sorted { $0.value != $1.value ? $0.value > $1.value : $0.key < $1.key }.prefix(3)
            .map { $0.value == 1 ? "\"\($0.key)\"" : "\"\($0.key)\" ×\($0.value)" }
        let more = counts.count > 3 ? ", …" : ""
        return "\(names.count) layers: \(top.joined(separator: ", "))\(more)"
    }
}
